# Generated by Django 6.0.2 on 2026-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_municipality_accommodation_touristspot_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipality',
            new_name='Province',
        ),
        migrations.AlterModelOptions(
            name='province',
            options={},
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='municipality',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='touristspot',
            old_name='municipality',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='transportationterminal',
            old_name='municipality',
            new_name='province',
        ),
        migrations.AddField(
            model_name='report',
            name='region',
            field=models.CharField(choices=[('Luzon', 'Luzon'), ('Visayas', 'Visayas'), ('Mindanao', 'Mindanao')], default='Luzon', max_length=20),
        ),
    ]
