# Generated by Django 6.0.5 on 2026-05-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_municipality_province_alter_province_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='RoomBooking',
        ),
    ]
